google_analytics: G-SSHGPM30RJ
baseurl: ""
title: Global DevOps Bootcamp
description: |
   Global DevOps Bootcamp is a worldwide community event that has now been organized for three years in a row. Each year, we create a full-day experience around a central theme.
   The day starts with a keynote (of a famous speaker!), a local keynote (by you!), and a challenging yet inspiring hackathon focusing on DevOps practices and Modern Software practices.
   People also learn about the latest trends and will be sharing their DevOps experiences. It’s a great opportunity to learn hands-on and network with others locally working in this space,
   and also get to hear all about some real-world DevOps experiences.

url: www.globaldevopsbootcamp.com

repository: globaldevopsbootcamp/gdbcwebsite

twitter:
  username: gdevopsbc
  card: summary

comments:
  provider: giscus
  giscus:
    repo_id              : MDEwOlJlcG9zaXRvcnk0MDEzNzgyMzc= # Shown during giscus setup at https://giscus.app
    category_name        : Announcements # Full text name of the category
    category_id          : DIC_kwDOF-yLvc4B-49m # Shown during giscus setup at https://giscus.app
    discussion_term      : # "pathname" (default), "url", "title", "og:title"
    reactions_enabled    : # '1' for enabled (default), '0' for disabled
    theme                : 'transparent_dark' # "light" (default), "dark", "dark_dimmed", "transparent_dark", "preferred_color_scheme"

plugins:
  - "jekyll-seo-tag"

exclude: [
  styles/index.css,
  styles/syntax.css,
  package.json,
  package-lock.json,
  postcss.config.js,
  readme.md,
]

# Defaults
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: false
      read_time: true
      comments: true
      share: true
      related: true
