google_analytics:
baseurl: /gdbcwebsite
title: Global DevOps Bootcamp
description: |
   Global DevOps Bootcamp is a worldwide community event that has now been organized for three years in a row. Each year, we create a full-day experience around a central theme.
   The day starts with a keynote (of a famous speaker!), a local keynote (by you!), and a challenging yet inspiring hackathon focusing on DevOps practices and Modern Software practices.
   People also learn about the latest trends and will be sharing their DevOps experiences. It’s a great opportunity to learn hands-on and network with others locally working in this space,
   and also get to hear all about some real-world DevOps experiences.

url: www.globaldevopsbootcamp.com

repository: globaldevopsbootcamp/gdbc-website

twitter:
  username: gdevopsbc
  card: summary

plugins:
  - "jekyll-seo-tag"

exclude: [
  styles/index.css,
  styles/syntax.css,
  package.json,
  package-lock.json,
  postcss.config.js,
  readme.md,
]

# Defaults
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: false
      read_time: true
      comments: # true
      share: true
      related: true